# goreleaser.yaml file builds the project for macOS, Linux, and Windows
# on amd64.
#
# See http://goreleaser.com
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
before:
  hooks:
    - go mod download
builds:
  - id: build_macos
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64

  - id: build_linux
    env:
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64

  - id: build_windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64

archives:
- replacements:
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  skip: true


release:
  github:
    owner: neilotoole
    name: sqlitr
  draft: false
  prerelease: auto

brews:
  -
    homepage: "https://github.com/neilotoole/sqlitr"
    description: "sqlitr is a trivial Go/CGo SQLite CLI"
    github:
      owner: neilotoole
      name: homebrew-sqlitr

scoop:
  # scoop is a package installer for Windows, like brew for macOS.
  # For background, see https://github.com/lukesampson/scoop/wiki/Buckets
#  bucket:
#    owner: neilotoole
#    name: sq
  homepage: "https://github.com/neilotoole/sqlitr"
  description: "sqlitr is a trivial Go/CGo SQLite CLI"

#    commit_author:
#      name: neilotoole
#      email: neilotoole@apache.org
#
##    folder: Formula
##
##    test: |
##      system "#{bin}/sq version"
##
##    install: |
##      bin.install "sq"
##    # Setting this will prevent goreleaser to actually try to commit the updated
##    # formula - instead, the formula file will be stored on the dist folder only,
##    # leaving the responsibility of publishing it to the user.
##    # If set to auto, the release will not be uploaded to the homebrew tap
##    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
##    # Default is false.
##    skip_upload: false

